import { COMMANDS, findCommand } from '../../lib/commands'

export type CommandLineStatus =
  | 'idle'
  | 'draft'
  | 'valid'
  | 'invalid'
  | 'incomplete'
  | 'executed'

export interface ParsedCommandLine {
  raw: string
  trimmed: string
  commandName: string
  query: string
  isIsolated: boolean
  definition: ReturnType<typeof findCommand>
}

const COMMAND_NAMES = COMMANDS.map((command) => command.name)

export function getToggleTitle(command: string): string {
  const map: Record<string, string> = {
    '/summarize': 'Summary generated by AI',
    '/table': 'Table generated by AI',
    '/define': 'Definition generated by AI',
    '/opinion': 'Opinion generated by AI',
    '/search': 'Search result generated by AI',
    '/profile': 'Profile generated by AI',
    '/expand': 'Expansion generated by AI',
    '/explain': 'Explanation generated by AI',
    '/guide': 'Study guide generated by AI',
    '/mindmap': 'Mind map generated by AI',
    '/ask': 'Response generated by AI',
    '/docs': 'Response generated by AI',
    '/week': 'Weekly answer generated by AI',
  }
  return map[command] ?? 'Response generated by AI'
}

export function isPotentialCommandLine(line: string): boolean {
  return /^\s*\//.test(line)
}

export function parseCommandLine(line: string): ParsedCommandLine | null {
  if (!isPotentialCommandLine(line)) return null
  const trimmed = line.trim()
  const match = trimmed.match(/^(\/[^\s]+)(?:\s+(.*))?$/)
  if (!match) {
    return {
      raw: line,
      trimmed,
      commandName: trimmed,
      query: '',
      isIsolated: true,
      definition: undefined,
    }
  }
  const commandName = match[1].toLowerCase()
  const query = (match[2] ?? '').trim()
  return {
    raw: line,
    trimmed,
    commandName,
    query,
    isIsolated: true,
    definition: findCommand(commandName),
  }
}

export function getCommandLineStatus(line: string, isCalendarNote = false): CommandLineStatus {
  const parsed = parseCommandLine(line)
  if (!parsed) return 'idle'
  if (!parsed.definition) return 'invalid'
  if (parsed.definition.calendarOnly && !isCalendarNote) return 'invalid'
  if (parsed.definition.takesQuery && parsed.query.length === 0) return 'incomplete'
  return 'valid'
}

export function getCommandSuggestions(input: string, isCalendarNote = false): string[] {
  const normalized = input.trim().toLowerCase()
  const availableNames = isCalendarNote
    ? COMMAND_NAMES
    : COMMAND_NAMES.filter((name) => !findCommand(name)?.calendarOnly)
  if (!normalized.startsWith('/')) return []
  if (normalized === '/') return availableNames
  return availableNames.filter((name) => name.toLowerCase().startsWith(normalized))
}
